spring.application.name=Spotify_Java
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/spotify
spring.datasource.username=user_java
spring.datasource.password=123
server.port=8080
spring.jackson.serialization.fail-on-empty-beans=false
logging.level.org.hibenate=ERROR
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
